"""empty message

Revision ID: 220f47a8a51c
Revises: 383262633701
Create Date: 2020-09-03 23:49:08.802510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220f47a8a51c'
down_revision = '383262633701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'release_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
