"""empty message

Revision ID: b87262d0e50a
Revises: 4361050bbd97
Create Date: 2020-08-28 01:07:10.586391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87262d0e50a'
down_revision = '4361050bbd97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'similar_artist', 'artist', ['artist2_id'], ['id'])
    op.create_foreign_key(None, 'similar_artist', 'artist', ['artist1_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'similar_artist', type_='foreignkey')
    op.drop_constraint(None, 'similar_artist', type_='foreignkey')
    # ### end Alembic commands ###
