"""empty message

Revision ID: fe37cb8c49af
Revises: 80fa497793f9
Create Date: 2020-09-03 22:04:24.352470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe37cb8c49af'
down_revision = '80fa497793f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('spotify_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'spotify_id')
    # ### end Alembic commands ###
