"""empty message

Revision ID: 383262633701
Revises: fe37cb8c49af
Create Date: 2020-09-03 23:43:57.155052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383262633701'
down_revision = 'fe37cb8c49af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('release_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'release_date')
    # ### end Alembic commands ###
