"""empty message

Revision ID: 4361050bbd97
Revises: 631b9395d09a
Create Date: 2020-08-28 00:18:44.760748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4361050bbd97'
down_revision = '631b9395d09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'album', ['id'])
    op.create_unique_constraint(None, 'artist', ['id'])
    op.create_unique_constraint(None, 'genre', ['id'])
    op.alter_column('similar_artist', 'match',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.drop_constraint('similar_artist_artist1_id_fkey', 'similar_artist', type_='foreignkey')
    op.drop_constraint('similar_artist_artist2_id_fkey', 'similar_artist', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('similar_artist_artist2_id_fkey', 'similar_artist', 'artist', ['artist2_id'], ['id'])
    op.create_foreign_key('similar_artist_artist1_id_fkey', 'similar_artist', 'artist', ['artist1_id'], ['id'])
    op.alter_column('similar_artist', 'match',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.drop_constraint(None, 'genre', type_='unique')
    op.drop_constraint(None, 'artist', type_='unique')
    op.drop_constraint(None, 'album', type_='unique')
    # ### end Alembic commands ###
