"""empty message

Revision ID: 80fa497793f9
Revises: b87262d0e50a
Create Date: 2020-09-03 22:01:12.647568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80fa497793f9'
down_revision = 'b87262d0e50a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('spotify_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'spotify_id')
    # ### end Alembic commands ###
