"""empty message

Revision ID: f232fbf85c60
Revises: 220f47a8a51c
Create Date: 2020-09-03 23:49:36.425013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f232fbf85c60'
down_revision = '220f47a8a51c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('release_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'release_date')
    # ### end Alembic commands ###
